### ISSUE TITLE
Some error occured

### ISSUE THREAD

**Issue by Jiks19** [payu-intrepos/payumoney-new-sample-app#1]
Hello,

I'm trying to make payment using live environment but not working...

Here I'm pasting the log I received:

payumoneySDK - login: {"event_id":"1","device_id":"29f2e4a21c1c248f","uuid":"3fedcfe3-f2c4-47e5-a2eb-f54a837078de","d_ua":"Mozilla\/5.0 (Linux; Android 6.0.1; Redmi Note 3 Build\/MMB29M; wv) AppleWebKit\/537.36 (KHTML, like Gecko) Version\/4.0 Chrome\/59.0.3071.125 Mobile Safari\/537.36","u_lat":"","u_lon":"","u_acu":"","app_id":"com.img.unitedway","package_name":"com.img.unitedway","app_version_name":"1.1","app_version_code":"2","d_locale":"en","d_ccid":"in","d_lang":"English","d_name":"Xiaomi","d_model":"Redmi Note 3","d_os":"Android","d_osv":"6.0.1","sdk_version":"7","sdk_build":"7.0.0","d_mfg":"Xiaomi","d_nw_type":"4G","d_ss":"0","d_scrn_sz":"5.7437176737064215","d_scrn_res":"1080 * 1920","m_id":"5251210","m_key":"h6zmjI","ip":"10.4.40.17","app_name":"United Way","d_ts":"1501690204995","env":"PRODUCTION"}
08-02 21:40:04.997 30688-30688/com.img.unitedway I/Timeline: Timeline: Activity_launch_request time:121087080
08-02 21:40:05.033 30688-30688/com.img.unitedway V/BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@b0e4c5
08-02 21:40:05.033 30688-30688/com.img.unitedway V/BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@6639e1a
08-02 21:40:05.045 30688-30688/com.img.unitedway D/ActivityThreadInjector: clearCachedDrawables.
08-02 21:40:05.967 30688-30688/com.img.unitedway I/Difference: [ main: SdkSession.java: 365: onResponse() ] --> URL=/payment/app/v1/addPaymentTime=926
08-02 21:40:06.051 30688-30688/com.img.unitedway D/MainActivity: request code 10000 resultcode 0

**Comment by mayur19** [comment]
The error is **definitely because of wrong hash generation.** I went through all these errors and logs.
You must need hash generator script on your server. I hope you are generating hash from server.
In case, if you don't have hash generator script [get it from here](https://gist.github.com/mayur19/26417eeba02f5e5ced8138f4d9040d6a)
Just replace your salt key on that file. Also remove switch case from code you have right now and add following code. Then set merchantHash to mPaymentParams. You can refer the question below for proper request and response handling using volley.

```
jsonObject = new JSONObject(response); 
merchantHash = jsonObject.getString("result");
```

And for reference go through[ this stackoverflow answer.](https://stackoverflow.com/a/47912707/5630823) Please read all comments in answer. You can also refer code from question.
Note: Hash generator algorithm is tested. Send all respective details properly. If possible, do not post any user defined variables.
